package de.dhbw.javaproject.notizverwaltung.controller;

import java.util.List;

import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import de.dhbw.javaproject.notizverwaltung.model.Notiz;
import de.dhbw.javaproject.notizverwaltung.DBAccess;

@RestController
public class notizverwaltungController 
{
	private List<Notiz> notizListe;
	
	DBAccess db = new DBAccess();
	
	@RequestMapping("/new")
	public @ResponseBody String save(@RequestParam String inhalt) throws Exception {
		db.addNotiz(inhalt);
		return "<html><head><meta http-equiv=\"refresh\" content=\"0; URL=http://localhost:8080/\"></head></html>";
	}
	
	@RequestMapping("/save")
	public @ResponseBody String save(@RequestParam int id, @RequestParam String inhalt) throws Exception {
		db.updateNotiz(id, inhalt);
		return "<html><head><meta http-equiv=\"refresh\" content=\"0; URL=http://localhost:8080/\"></head></html>";
	}
	
	@RequestMapping("/")
	public String home() throws Exception {
		
		this.notizListe = db.getNotizen();
		
		String html1 = "<!DOCTYPE html>\n"
				+ "<html lang=\"de-DE\">\n"
				+ "<style>\n"
				+ "*{\n"
				+ "  font-family: Roboto, Arial, Helvetica, sans-serif;\n"
				+ "  box-sizing: border-box;\n"
				+ "}\n"
				+ "html{\n"
				+ "  background-color: white;\n"
				+ "}\n"
				+ ".noDisp {\n"
				+ "  display: none;\n"
				+ "}\n"
				+ "#mobileOnly{\n"
				+ "  display: none;\n"
				+ "}\n"
				+ "#nav {\n"
				+ "  position: fixed;\n"
				+ "  top: 0;\n"
				+ "  left: 0;\n"
				+ "  vertical-align: middle;\n"
				+ "  width: 100%;\n"
				+ "  background-color: #0D79FF;\n"
				+ "  color: white;\n"
				+ "  opacity: 0.95;\n"
				+ "  z-index: 9999;\n"
				+ "}\n"
				+ "#banner{\n"
				+ "  background-position: center;\n"
				+ "  background-size: cover;\n"
				+ "  background-repeat: no-repeat;\n"
				+ "  background-attachment: local;\n"
				+ "  position: relative;\n"
				+ "  display: flex;\n"
				+ "  justify-content: left;\n"
				+ "  align-items: center;\n"
				+ "}\n"
				+ "#banner h1{\n"
				+ "  font-size: 3em;\n"
				+ "  text-shadow: 0px 0px 5px black;\n"
				+ "  color: white;\n"
				+ "}\n"
				+ "\n"
				+ "#contentWrapper2 p{\n"
				+ "  text-align: left;\n"
				+ "}\n"
				+ "#contentWrapper2 p img{\n"
				+ "  max-width: 100%;\n"
				+ "}\n"
				+ "#contentWrapper2 a{\n"
				+ "  font-size: inherit;\n"
				+ "  font-weight: inherit;\n"
				+ "  font-style: inherit;\n"
				+ "  color: inherit;\n"
				+ "}\n"
				+ "\n"
				+ "#footer2{ color: grey; }\n"
				+ "#f2c{ color: lightblue; }\n"
				+ "\n"
				+ "\n"
				+ "@media only screen and (max-width: 910px){    /*Smartphones*/\n"
				+ "  #logoFrame{\n"
				+ "    height: 50px;\n"
				+ "    width: 60%;\n"
				+ "    margin-left: 20px;\n"
				+ "    overflow: hidden;\n"
				+ "    position: fixed;\n"
				+ "    text-align: left;\n"
				+ "  }\n"
				+ "  #logo{\n"
				+ "    display: inline-block;\n"
				+ "    height: 100%;\n"
				+ "    padding: 1%;\n"
				+ "    width: auto;\n"
				+ "    float: left;\n"
				+ "    z-index: 99999;\n"
				+ "  }\n"
				+ "  /***************** Menü ****************/\n"
				+ "  #BurgerMenu{    /* Button für das Burger Menü */\n"
				+ "    float: right;\n"
				+ "    margin: 5px 20px 5px 5px;\n"
				+ "    background:none;\n"
				+ "    border:0;\n"
				+ "    outline: none;\n"
				+ "    display: inline-block;\n"
				+ "    z-index: 11;\n"
				+ "  }\n"
				+ "  #linie1, #linie2, #linie3 {   /* 3 Striche im Burger Menü */\n"
				+ "    z-index: 12;\n"
				+ "    width: 35px;\n"
				+ "    height: 5px;\n"
				+ "    background-color: black;\n"
				+ "    margin: 6px 0;\n"
				+ "    transition: 0.5s;\n"
				+ "  }\n"
				+ "  #nav{\n"
				+ "    z-index: 10;\n"
				+ "    font-weight: bold;\n"
				+ "    height: 50px;\n"
				+ "    text-align: right;\n"
				+ "    transition: opacity 0.5s;\n"
				+ "    list-style-type: none;\n"
				+ "  }\n"
				+ "  /***************** New Nav ****************/\n"
				+ "  #navUlDiv {\n"
				+ "    height: 100%;\n"
				+ "    width: 0;\n"
				+ "    position: fixed;\n"
				+ "    z-index: 1;\n"
				+ "    top: 50px;\n"
				+ "    right: 0;\n"
				+ "    background-color: rgb(0,0,0);\n"
				+ "    background-color: rgba(0,0,0, 0.9);\n"
				+ "    overflow-x: hidden;\n"
				+ "    transition: 0.5s;\n"
				+ "  }\n"
				+ "  #navUl {\n"
				+ "    position: relative;\n"
				+ "    width: 100%;\n"
				+ "    text-align: center;\n"
				+ "    margin-top: 30px;\n"
				+ "    padding-left: 0;\n"
				+ "    font-variant: all-small-caps;\n"
				+ "  }\n"
				+ "  #navUl a {\n"
				+ "    text-decoration: none;\n"
				+ "    font-size: 2.5em;\n"
				+ "    color: #9f9f9f;\n"
				+ "    display: block;\n"
				+ "    transition: 0.3s;\n"
				+ "    line-height: 2;\n"
				+ "  }\n"
				+ "  #navUl a:hover, #navUl a:focus {\n"
				+ "    color: #559eff;\n"
				+ "  }\n"
				+ "  .sub-nav {\n"
				+ "    padding-left: 0;\n"
				+ "    display: none;\n"
				+ "  }\n"
				+ "  .sub-nav li{\n"
				+ "    color: #cce8ff;\n"
				+ "    font-size: 0.7em;\n"
				+ "    line-height: 1.5;\n"
				+ "  }\n"
				+ "  #navUl li:hover .sub-nav{\n"
				+ "    list-style-type: none;\n"
				+ "    display: block;\n"
				+ "  }\n"
				+ "\n"
				+ "  body{\n"
				+ "    margin: 0;\n"
				+ "    padding: 0;\n"
				+ "    width: 100%;\n"
				+ "  }\n"
				+ "  a{\n"
				+ "    color: inherit;\n"
				+ "  }\n"
				+ "\n"
				+ "\n"
				+ "  /***************** Main ****************/\n"
				+ "  #banner{\n"
				+ "    height: 200px;\n"
				+ "    margin-top: 50px;\n"
				+ "  }\n"
				+ "  #banner h1{\n"
				+ "    margin: auto auto 5px 5%;\n"
				+ "    font-size: 1.8em;\n"
				+ "  }\n"
				+ "  #banner span{\n"
				+ "    margin: auto 5px 5px auto;\n"
				+ "    color: white;\n"
				+ "    font-size: 0.8em;\n"
				+ "    text-align: right;\n"
				+ "  }\n"
				+ "  #contentWrapper2{\n"
				+ "    width: 100%;\n"
				+ "    padding: 20px;\n"
				+ "    font-size: 1.1em;\n"
				+ "    color: black;\n"
				+ "    line-height: 1.5;\n"
				+ "    background-color: #1f1f1f1f;\n"
				+ "  }\n"
				+ "  table {\n"
				+ "    border-collapse: collapse;\n"
				+ "    border-spacing: 0;\n"
				+ "    width: 100%;\n"
				+ "  }\n"
				+ "  th, td {\n"
				+ "    text-align: left;\n"
				+ "    padding: 3px;\n"
				+ "  }\n"
				+ "  tr:nth-child(odd) {\n"
				+ "    background-color: lightgrey;\n"
				+ "  }\n"
				+ "  #footer {\n"
				+ "    position: absolute;\n"
				+ "    width: 100%;\n"
				+ "  }\n"
				+ "  #footer1 {\n"
				+ "    height: 70px;\n"
				+ "    width: 100%;\n"
				+ "    padding: 1px 0;\n"
				+ "    font-size: 1.2em;\n"
				+ "    line-height: 1.5;\n"
				+ "    text-align: center;\n"
				+ "    background-color: #0DB9FF;\n"
				+ "  }\n"
				+ "  #footer2 {\n"
				+ "    height: 550px;\n"
				+ "    width: 100%;\n"
				+ "    text-align: center;\n"
				+ "    line-height: 1.5;\n"
				+ "    color: grey;\n"
				+ "    background-color: #343434;\n"
				+ "  }\n"
				+ "  #linkIG:hover{\n"
				+ "    color: #AA5082;\n"
				+ "    transition-duration: 0.3s;\n"
				+ "  }\n"
				+ "  #linkFB:hover{\n"
				+ "    color: #4267B2;\n"
				+ "    transition-duration: 0.3s;\n"
				+ "  }\n"
				+ "  #footer a{\n"
				+ "    text-decoration: underline;\n"
				+ "    font-size: 1em;\n"
				+ "    color: inherit;\n"
				+ "  }\n"
				+ "  #footer2 a:hover{\n"
				+ "    color: white;\n"
				+ "    transition-duration: 0.3s;\n"
				+ "  }\n"
				+ "  #f2l{\n"
				+ "    width: 100%;\n"
				+ "    float: left;\n"
				+ "    padding: 0 0 0 0;\n"
				+ "    line-height: 1.5em;\n"
				+ "  }\n"
				+ "  #f2c{\n"
				+ "    width: 100%;\n"
				+ "    float: left;\n"
				+ "    padding: 0;\n"
				+ "    line-height: 1.5em;\n"
				+ "  }\n"
				+ "  #f2r{\n"
				+ "    width: 100%;\n"
				+ "    float: right;\n"
				+ "    padding: 0;\n"
				+ "    line-height: 1.5em;\n"
				+ "  }\n"
				+ "}\n"
				+ "\n"
				+ "@media only screen and (min-width: 910px) {   /******PC*******/\n"
				+ "  * {\n"
				+ "    margin: 0px;\n"
				+ "  }\n"
				+ "  #site {\n"
				+ "    width: 100%;\n"
				+ "  }\n"
				+ "  /***************** Menü ****************/\n"
				+ "  #BurgerMenu {\n"
				+ "    display: none; /* ausgeblendet auf PC*/\n"
				+ "  }\n"
				+ "  #logo {\n"
				+ "    display: inline-block;\n"
				+ "    height: 100%;\n"
				+ "    padding: 2%;\n"
				+ "    width: auto;\n"
				+ "    float: left;\n"
				+ "    z-index: 9999;\n"
				+ "  }\n"
				+ "  #logoFrame {\n"
				+ "    display: inline-block;\n"
				+ "    height: 100%;\n"
				+ "    margin: auto 0px auto 25px;\n"
				+ "    z-index: 9999;\n"
				+ "  }\n"
				+ "  #nav {\n"
				+ "    /* Navbar mit logo*/\n"
				+ "    padding: 0;\n"
				+ "    margin: 0;\n"
				+ "    line-height: 100px;\n"
				+ "    vertical-align: middle;\n"
				+ "    height: 100px;\n"
				+ "    opacity: 0.95;\n"
				+ "    z-index: 9999;\n"
				+ "  }\n"
				+ "  #navUlDiv {\n"
				+ "    /* Navigation*/\n"
				+ "    float: right;\n"
				+ "    margin: inherit;\n"
				+ "    height: inherit;\n"
				+ "  }\n"
				+ "  #navUl {\n"
				+ "    /* Navigation Liste*/\n"
				+ "    height: inherit;\n"
				+ "    display: inline-block;\n"
				+ "    float: right;\n"
				+ "    margin-top: 0;\n"
				+ "    margin-bottom: 0;\n"
				+ "    padding-left: 0;\n"
				+ "    font-variant: all-small-caps;\n"
				+ "  }\n"
				+ "  #navUl li {\n"
				+ "    /* Die 4 Menüpunkte (und subnavs)*/\n"
				+ "    text-align: center;\n"
				+ "    float: left;\n"
				+ "    height: 100%;\n"
				+ "    width: 130px;\n"
				+ "    list-style-type: none;\n"
				+ "  }\n"
				+ "  #fliegenlernen{\n"
				+ "    padding: 20px 0;\n"
				+ "    line-height: 30px;\n"
				+ "  }\n"
				+ "  #navUl li:hover {\n"
				+ "    background-color: #0C6EE8;\n"
				+ "  }\n"
				+ "  /* Menüpunkte hover*/\n"
				+ "    a {\n"
				+ "    /* Text Menüpunkte*/\n"
				+ "    text-align: center;\n"
				+ "    height: 100%;\n"
				+ "    width: 100%;\n"
				+ "    color: white;\n"
				+ "    text-decoration: none;\n"
				+ "    font-size: 1.6em;\n"
				+ "  }\n"
				+ "  .uld{\n"
				+ "    font-size: 1.35em;\n"
				+ "  }\n"
				+ "  /* Text Untermenüpunkte*/\n"
				+ "  #navUl li:hover a {\n"
				+ "    color: white;\n"
				+ "  }\n"
				+ "  #navUl li:hover ul {\n"
				+ "    /*display: block;*/\n"
				+ "    opacity: 100;\n"
				+ "    height: 50px;\n"
				+ "  }\n"
				+ "  /* Subnav anzeigen bei menü hover*/\n"
				+ "  #navUl li ul {\n"
				+ "    /* Subnav*/\n"
				+ "    line-height: 50px;\n"
				+ "    padding: 0;\n"
				+ "    margin-top: -2px;\n"
				+ "    opacity: 0;\n"
				+ "    height: 0px;\n"
				+ "  }\n"
				+ "  #navUl li ul li {\n"
				+ "    /* Menüpunkte im Subnav*/\n"
				+ "    float: none;\n"
				+ "    background-color: #0DB9FF;\n"
				+ "  }\n"
				+ "\n"
				+ "  #navUl li ul li:hover {\n"
				+ "    background-color: #0C6EE8;\n"
				+ "  }\n"
				+ "\n"
				+ "  #banner{\n"
				+ "    height: 350px;\n"
				+ "    margin-top: 100px;\n"
				+ "  }\n"
				+ "  #banner h1{\n"
				+ "    margin: auto auto 25px 5%;\n"
				+ "    max-width: 90%;\n"
				+ "    letter-spacing: 0.04em;\n"
				+ "  }\n"
				+ "  #banner span{\n"
				+ "    margin: auto 10px 5px auto;\n"
				+ "    color: white;\n"
				+ "    font-size: 0.9em;\n"
				+ "    text-align: right;\n"
				+ "  }\n"
				+ "\n"
				+ "  /***************** Main ****************/\n"
				+ "  #contentWrapper2{\n"
				+ "    width: 90%;\n"
				+ "    margin: 20px 20% 50px 5%;\n"
				+ "    padding: 30px;\n"
				+ "    font-size: 1.1em;\n"
				+ "    color: black;\n"
				+ "    line-height: 1.8;\n"
				+ "    background-color: #1f1f1f1f;\n"
				+ "  }\n"
				+ "  #contentWrapper2 iframe{\n"
				+ "    border: 2px solid darkgray;\n"
				+ "    border-radius: 5px;\n"
				+ "  }\n"
				+ "  table {\n"
				+ "    border-collapse: collapse;\n"
				+ "    border-spacing: 0;\n"
				+ "    width: 100%;\n"
				+ "  }\n"
				+ "  th, td {\n"
				+ "    text-align: left;\n"
				+ "    padding: 5px;\n"
				+ "  }\n"
				+ "  tr:nth-child(odd) {\n"
				+ "    background-color: lightgrey;\n"
				+ "  }\n"
				+ "  /***************** Footer ****************/\n"
				+ "  #footer {\n"
				+ "    position: absolute;\n"
				+ "    width: 100%;\n"
				+ "  }\n"
				+ "  #footer1 {\n"
				+ "    width: 100%;\n"
				+ "    padding: 20px 0;\n"
				+ "    font-size: 1.2em;\n"
				+ "    text-align: center;\n"
				+ "    background-color: #0DB9FF;\n"
				+ "  }\n"
				+ "  #footer2 {\n"
				+ "    height: 260px;\n"
				+ "    width: 100%;\n"
				+ "    text-align: center;\n"
				+ "    background-color: #343434;\n"
				+ "  }\n"
				+ "  #linkIG:hover{\n"
				+ "    color: #AA5082;\n"
				+ "    transition-duration: 0.3s;\n"
				+ "  }\n"
				+ "  #linkFB:hover{\n"
				+ "    color: #4267B2;\n"
				+ "    transition-duration: 0.3s;\n"
				+ "  }\n"
				+ "  #footer a{\n"
				+ "    text-decoration: underline;\n"
				+ "    font-size: 1em;\n"
				+ "    color: inherit;\n"
				+ "  }\n"
				+ "  #footer2 a:hover{\n"
				+ "    color: white;\n"
				+ "    transition-duration: 0.3s;\n"
				+ "  }\n"
				+ "  #f2l{\n"
				+ "    width: 35%;\n"
				+ "    float: left;\n"
				+ "    text-align: left;\n"
				+ "    padding: 25px 3%;\n"
				+ "    line-height: 1.8em;\n"
				+ "  }\n"
				+ "  #f2c{\n"
				+ "    width: 30%;\n"
				+ "    float: left;\n"
				+ "    text-align: center;\n"
				+ "    padding: 25px 0;\n"
				+ "    line-height: 1.8em;\n"
				+ "  }\n"
				+ "  #f2r{\n"
				+ "    width: 35%;\n"
				+ "    float: right;\n"
				+ "    text-align: right;\n"
				+ "    padding: 25px 3%;\n"
				+ "    line-height: 1.8em;\n"
				+ "  }\n"
				+ "\n"
				+ "}\n"
				+ "\n"
				+ "@media only screen and (min-width: 1000px) {\n"
				+ "  #banner h1{\n"
				+ "    margin: auto auto 25px 10%;\n"
				+ "    max-width: 85%;\n"
				+ "  }\n"
				+ "  #contentWrapper2{\n"
				+ "    width: 80%;\n"
				+ "    margin: 20px 10% 50px 10%;\n"
				+ "  }\n"
				+ "}\n"
				+ "\n"
				+ "@media only screen and (min-width: 1200px) {\n"
				+ "  #navUl li {\n"
				+ "    width: 160px;\n"
				+ "  }\n"
				+ "  #fliegenlernen{\n"
				+ "    padding: 0;\n"
				+ "    line-height: 100px;\n"
				+ "  }\n"
				+ "  #banner h1{\n"
				+ "    margin: auto auto 25px 15%;\n"
				+ "    max-width: 75%;\n"
				+ "  }\n"
				+ "  #contentWrapper2{\n"
				+ "    width: 70%;\n"
				+ "    margin: 20px 15% 50px 15%;\n"
				+ "  }\n"
				+ "}\n"
				+ "\n"
				+ "@media only screen and (min-width: 1500px) {\n"
				+ "  #banner h1{\n"
				+ "    margin: auto auto 25px 20%;\n"
				+ "    max-width: 65%;\n"
				+ "  }\n"
				+ "  #contentWrapper2{\n"
				+ "    width: 60%;\n"
				+ "    margin: 20px 20% 50px 20%;\n"
				+ "  }\n"
				+ "}\n"
				+ "\n"
				+ "</style>\n"
				+ "<head>\n"
				+ "    <meta charset=\"utf-8\">\n"
				+ "\n"
				+ "    <meta name=\"theme-color\" content=\"#ffffff\">\n"
				+ "\n"
				+ "    <link href=\"https://fonts.googleapis.com/css?family=Roboto\" rel=\"stylesheet\">\n"
				+ "    <link rel=\"stylesheet\" type=\"text/css\" href=\"/site/templates/styles/style.css\">\n"
				+ "    <script language=\"javascript\" type=\"text/javascript\" src=\"/site/templates/scripts/jquery-3.3.1.min.js\"></script>\n"
				+ "\n"
				+ "	<title>Notizbuch</title>\n"
				+ "\n"
				+ "</head><body>\n"
				+ "<div id=\"site\">\n"
				+ "    <!-- - - - - - - - - - - - - - - - - - - Logo - - - - - - - - - - - - - - - - - - - -->\n"
				+ "    <div id=\"nav\" class=\"navbar-fixed-top\">\n"
				+ "<h1 style=\"margin-left:20px;\">Notizbuch</h1>\n"
				+ "    </div>\n"
				+ "    <div id=\"banner\" style=\"background-image: url(https://w5.giffitsstatic.com/pics/c504/328346_5.jpg);\">\n"
				+ "\n"
				+ "    </div>\n"
				+ "\n"
				+ "    <div id=\"contentWrapper2\">\n";
		String html2 =  "        "
				+ "\n"
				+ "    </div>\n"
				+ "    <div id=\"footer\">\n"
				+ "        <div id=\"footer1\">\n"
				+ "\n"
				+ "        </div>\n"
				+ "        <div id=\"footer2\">\n"
				+ "            <div id=\"f2l\">\n"
				+ "\n"
				+ "            </div>\n"
				+ "            <div id=\"f2c\">\n"
				+ "<p>Notizbuch von Julian und David</p>\n"
				+ "            </div>\n"
				+ "            <div id=\"f2r\">\n"
				+ "\n"
				+ "            </div>\n"
				+ "        </div>\n"
				+ "    </div>\n"
				+ "</div>\n"
				+ "</body>\n"
				+ "\n"
				+ "</html>\n";
		
		String str = html1
				+ "<h2>Notizen</h2>\n" 
				+ "<table>"
				+ "	<tr>"
				+ "		<th>ID</th>"
				+ "		<th>Notiz</th>"
				+ "		<th> </th>"
				+ "	</tr> " ;
		
		for( Notiz n : notizListe) {
			str = str + "<tr>"
					+ "<form action=\"/save\" Method=\"GET\">"
					+ "<td> <input name=\"id\" type=\"text\" value=\"" + n.getID() + "\" /></td> "
					+ "<td> <input name=\"inhalt\" type=\"input\" value=\"" + n.getInhalt() + "\" /> </td>"
					+ "<td> <input name=\"speichern\" type=\"submit\"/></td> </form> </tr>";
		}
		
		str = str + "</table>"
				+ "<h2>Neue Notiz</h2>"
				+ "<form action=\"/new\" Method=\"GET\">"
				+ "<input name=\"inhalt\" type=\"input\" />"
				+ "<input name=\"speichern\" type=\"submit\"/> "
				+ "</form>"
				+ html2;
		
		return (str);

	}
	
}